module.exports = {
  'कंप्यूटर': 'computer',
  'कीबोर्ड': 'keyboard',
  'कुंजीपट': 'keyboard',
  'कुंजीपटल':'keyboard',
  'टिकट': 'ticket', 
  'कम्प्यूटर':'computer',
  'लैपटॉप':'Laptop',
  'माउस':'mouse',
  'अंग्रेज़ी':'english',
  'माइक्रोफोन':'microphone',
  'स्पीकर':'speaker',
  'डेस्कटॉप':'desktop',
  'सर्वर': 'server',
  'स्थिति':'status',
  'अद्यतन': 'update',
  'मुसीबत शूटिंग':'trouble shooting',
  'रीसेट':'reset',
  'पासवर्ड':'password',
  'मेरा लोकतांत्रिक':'my Uni hub',
  'मेरालोकतांत्रिक':'myUnihub',
  'विप्रो':'Wipro',
  'विज़ी':'Wipro',
  'स्क्रीन':'screen',
  'मॉनीटर':'monitor',
  'एसओ':'SSO',
  'प्रमाणीकरण':'authentication',
  'सत्यापन':'authentication',
  'सॉफ्टवेयर':'software',
  'रिबूट':'reboot',
  'नेटवर्क':'network',
};